### ISSUE TITLE
[DOC] broken link to babyAFQ in data/fetch.py

### ISSUE THREAD

**Issue by chiuhoward** [tractometry/pyAFQ#11]
https://github.com/tractometry/pyAFQ/blob/bc70f3947dba6230835b3f045d082a896a15b1c9/AFQ/data/fetch.py#L206

I think this is a broken link. `https://github.com/yeatmanlab/AFQ/tree/babyAFQ` works but I am not sure if that’s the intended target.

**Comment by arokem** [comment]
Yeah - that line makes no sense (IIUC, it's pointing to a branch that no
longer exists). I think we can simply delete it.

**Comment by arokem** [comment]
Closed by #12
