### ISSUE TITLE
[ENH] Compatibility with QSIrecon output (.tck.gz)

### ISSUE THREAD

**Issue by chiuhoward** [tractometry/pyAFQ#14]
I am currently running pyAFQ version 1.3.6.dev2861270539.

https://github.com/tractometry/pyAFQ/blob/1bbfc68144e7d8656df6cccfc0bbd593f0f9dd4e/AFQ/tasks/segmentation.py#L54

QSIrecon now generates `.tck.gz` outputs (https://qsirecon.readthedocs.io/en/latest/builtin_workflows.html#mrtrix-dwi-outputs) which I am unable to import directly into pyAFQ. The object initializes but the tractogram cannot be passed into tg (`UnboundLocalError: cannot access local variable 'tg' where it is not associated with a value`).

Manually unzipping the file to `.tck` and importing it in that format seems to work, but i was wondering if there was a way to automate this for multiple subjects (or somehow make pyAFQ compatible with `.tck.gz` input files? I am currently importing the tractogram by providing the path to the tck file through the `import_tract` kwarg in participantAFQ.

Will look at https://stackoverflow.com/questions/31028815/how-to-unzip-gz-file-using-python/44712152#44712152 to see if I can cobble up with a suggestion myself, but otherwise filing an issue for documentation.

**Comment by arokem** [comment]
Closed by #15
