### ISSUE TITLE
Python 3.12? 

### ISSUE THREAD

**Issue by htakemur** [tractometry/pyAFQ#40]
Hi all,

One of my colleagues said that he got an error message in pyAFQ when he tested pyAFQ under Python 3.12 ("subprocess-exited-with-error”). This issue was not replicated in Python 3.11. 

Therefore, my guess is that this may be related to some version update issue to Python 3.12. 
I know that Python 3.12 removed some of the modules (see example; https://community.mrtrix.org/t/dwifslpreproc-mrtrix-py/7618/3), and this may cause issues in some of the software. 

I think that my question is: should we stay on Python 3.11 for a while, or are there any plans for testing pyAFQ in Python 3.12?

**Comment by arokem** [comment]
We don't yet support 3.12 yet, so it's best to use 3.11 for now. 

That said, I think we should support 3.12 (at least?) in pyAFQ 2.0, so I'll leave this open for now and tag it for the pyAFQ 2.0 milestone.

**Comment by htakemur** [comment]
@arokem  Thank you very much for your response!
